[package]
name = "ttdl"
version = "3.1.0"
authors = ["Hauptling12 <Hauptling12@outlook.com>"]
edition = "2022"
keywords = ["todotxt", "terminal", "cli", "todo", "tasks"]
license = "MIT"
description = "TTDL - Terminal ToDo List manager"
readme = "intro.md"
repository = "https://github.com/Hauptling12/rodo"
categories = ["command-line-utilities"]

[profile.release]
lto = true

[dependencies]
todo_lib = "4.0"
getopts = "0.2"
chrono = "^0.4"
textwrap = "0.11"
lazy_static = "1.0"
caseless = "0.2.1"
dirs = "1.0"
toml = "0.4"
atty = "0.2"
term_size = "0.3.1"
termcolor = "1.0.4"
serde = "1.0"
serde_derive = "1.0.84"
json = "0.12"
unicode-width="0.1"

[package.metadata.deb]
section = "utility"
depends = "$auto"
priority = "optional"
assets = [
	["target/release/ttdl", "usr/bin/", "755"],
	["LICENSE", "usr/share/doc/ttdl/", "644"],
	["README.md", "usr/share/doc/ttdl/README", "644"],
	["ttdl.toml", "usr/share/doc/ttdl/ttdl.toml", "644"],
]
extended-description = """\
A powerful terminal todo list manager. It keeps the list in todo.txt format.\
"""
changelog = "changelog"
